# -*- conf -*-

# For documentation on these options, see `man fnott.ini`

# Global values
# output=<undefined>#
min-width=300
# min-width=0
max-width=300
# max-width=0
# max-height=0
# stacking-order=bottom-up
# anchor=top-right
# edge-margin-vertical=10
# edge-margin-horizontal=10
# notification-margin=10
# icon-theme=hicolor
# max-icon-size=32
# selection-helper=dmenu
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top
background=282a36dd
# background=3f5f3fff

border-color=bd93f9ff
# border-color=909090ff
# border-radius=0
border-size=2
# border-size=1

# padding-vertical=20
# padding-horizontal=20

dpi-aware=no
# dpi-aware=no

title-font="sans serif:pixelsize=16"
title-color=8be9fdff
# title-color=ffffffff
# title-format=<i>%a%A</i>

summary-font="sans serif:pixelsize=16"
# summary-color=ffffffff
# summary-format=<b>%s</b>\n

body-font="sans serif:pixelsize=16"
body-color=f8f8f2ff
# body-color=ffffffff
# body-format=%b

# progress-bar-height=20
progress-color=ffb86cff
# progress-color=ffffffff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
# max-timeout=0
# default-timeout=0
# idle-timeout=0

[low]
border-color=bd93f9aa
# background=2b2b2bff
# title-color=888888ff
# body-color=888888ff
summary-color=f1fa8cff

[normal]
border-color=bd93f9ff
summary-color=50fa7bff

[critical]
# background=6c3333ff
border-color=ff5555ff
summary-color=ff5555ff
